### ISSUE TITLE
[FEAT]: 'How to Build' documentation

### ISSUE THREAD

**Issue by kvithayathil** [AndroidDev-social/MastodonCompose#128]
### Description

Could we have a section on the documentation on how to build the project for each target? I've not worked with KMP but I imagine there's some nuances between building for iOS vs Android vs other platforms

**Comment by thebino** [comment]
Hi, there is already a detailed explanation here:
https://github.com/AndroidDev-social/DodoForMastodon/blob/main/CONTRIBUTING.md#-build

If this does not help, please re-open and I'll try to support
