### ISSUE TITLE
[FEAT]: Add iOS targets to existing modules

### ISSUE THREAD

**Issue by r-gurzkowski** [AndroidDev-social/MastodonCompose#39]
### Description

We should add iOS targets to our modules (data and domain layers) as early as possible, even without creating the iOS project. This way we will prevent putting jvm specific code to the common source sets.

**Comment by bitPogo** [comment]
Only if you can run iOS or the CI is setup.

**Comment by thebino** [comment]
There is already a base setup in these layers.

https://github.com/AndroidDev-social/MastodonCompose/blob/main/data/network/build.gradle.kts#L36
