### ISSUE TITLE
[FEAT]: Find a good / meaningful name

### ISSUE THREAD

**Issue by thebino** [AndroidDev-social/MastodonCompose#8]
### Description

When talking about a product it is mandatory to have a proper name which can be remembered and linked to its functionality.
Like the community once came up with [Boaty McBoatface](https://en.wikipedia.org/wiki/Boaty_McBoatface) we should be able to find some good names as well.

Let's first collect some ideas and later on we can start a poll for the decision.

**Comment by hrules6872** [comment]
Mastodonte 👍🏼 
which is Mastodon translated into Spanish https://www.wordreference.com/es/en/translation.asp?spen=mastodonte

**Comment by waseefakhtar** [comment]
Mammut

Reference:
<img width="1595" alt="Screenshot 2022-11-08 at 8 57 53 PM" src="https://user-images.githubusercontent.com/4093820/200613705-b6e52bb9-61d1-4887-bde4-f6e06ec32947.png">

**Comment by JacquesSmuts** [comment]
Mammut already exists as a Mastodon Android app, though not a very active one atm.
https://github.com/jamiesanson/Mammut

**Comment by JacquesSmuts** [comment]
Woolly

**Comment by evant** [comment]
Kdon (not serious but felt like we needed the obligatory suggestion with a K in it)
